name: Integração Contínua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Subir Banco de Dados
      run: docker compose up -d postgres

    - name: Análise de Código com GolangCI-Lint
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app golangci/golangci-lint \
        golangci-lint run controllers/ database/ models/ routes/

    - name: Executar Testes
      run: go test -v ./...
